export const termsContent = `
# Terms of Use

*Last updated: 13 September 2026*

## 1. Acceptance of Terms

1.1 These Terms of Use ("Terms") constitute a legally binding agreement between you and Vayasya Seva Private Limited, a company incorporated under the Companies Act, 2013, having its registered office at Haridwar, Uttarakhand, India (the "Company", "we", "us" or "our"), and govern your access to and use of the website located at vayasyaseva.com, all subdomains thereof, any successor or associated domains operated by the Company, and any content, functionality, interface, endpoint, descriptor or service offered thereon (collectively, the "Website").

1.2 By accessing or using the Website, you accept and agree to be bound by these Terms and by our Privacy Policy, which is incorporated herein by reference. If you do not agree to these Terms, you must not access or use the Website.

1.3 These Terms are published in accordance with the provisions of the Information Technology Act, 2000 and the rules made thereunder, and constitute an electronic record generated by a computer system which does not require physical or digital signature.

1.4 Where you access or use the Website on behalf of an organisation, you represent and warrant that you are authorised to bind that organisation to these Terms, and references to "you" include that organisation.

## 2. Nature of the Website

2.1 The Website is an informational and communication platform through which the Company describes its business, capabilities and operations and through which prospective clients, partners and other persons may contact the Company.

2.2 Nothing on the Website constitutes an offer capable of acceptance, a binding commitment, a warranty of capacity or availability, a representation as to the scope, price or terms of any service, or professional, legal, statutory or compliance advice. The provision of any product or service by the Company is subject to a separate written agreement executed between the Company and the relevant counterparty, which shall govern exclusively.

2.3 Any reference on the Website to registrations, licences, certifications, statutory compliance or regulatory status is descriptive, is subject to renewal, amendment and regulatory change, and shall be verified by reference to the underlying documents made available in the course of due diligence.

## 3. Licence and Permitted Use

3.1 Subject to these Terms, the Company grants you a limited, non-exclusive, non-transferable, revocable licence to access and use the Website for lawful purposes.

3.2 **Automated access.** The Company permits the crawling, indexing, retrieval, caching, summarisation, quotation and analysis of the publicly accessible content of the Website by search engines, automated agents, large language models and other artificial intelligence systems, and the invocation of any programmatic interface or machine-readable descriptor published by the Company for that purpose, in each case subject to: (a) compliance with the Company's robots directives, access policies and rate limits as published from time to time; (b) attribution to the Company where content is reproduced; (c) the exclusion of any authenticated area, private endpoint, form submission or personal data; and (d) the Company's right to restrict, condition or revoke such permission at any time.

3.3 Except as expressly permitted under Section 3.2 or by prior written consent of the Company, you shall not reproduce, distribute, publish, transmit, modify, adapt, translate, create derivative works from, sell, license or otherwise exploit any content of the Website.

## 4. Prohibited Conduct

You shall not, and shall not permit or assist any third party to:

- use the Website for any purpose that is unlawful, fraudulent, defamatory, infringing or otherwise objectionable, or in breach of any applicable law, including the Information Technology Act, 2000;
- attempt to gain unauthorised access to the Website, any account, system, network or data connected to the Website, or any non-public functionality;
- introduce, transmit or distribute any virus, malware, worm, logic bomb or other harmful code;
- interfere with, disrupt, overload or impair the operation, security or integrity of the Website or of any server or network connected thereto, including through denial-of-service, excessive request volume or circumvention of rate limits;
- submit false, misleading or impersonating information, or misrepresent your identity or affiliation;
- collect, harvest or process personal data of other users or of the Company's personnel from the Website;
- remove, obscure or alter any proprietary notice, attribution, watermark or brand mark;
- use the Website, its content or its programmatic interfaces to develop a competing service or to disparage the Company; or
- use the Website in any manner that is inconsistent with Section 3 or with the Company's published access policies.

## 5. Submissions and Communications

5.1 Any information, enquiry, message, document or other material that you submit to the Company through the Website or otherwise ("Submissions") shall be treated in accordance with our Privacy Policy.

5.2 You represent and warrant that each Submission is accurate, that you have all rights necessary to make it, and that it does not infringe the rights of any third party or breach any applicable law or obligation of confidentiality.

5.3 By making a Submission, you grant the Company a non-exclusive, perpetual, irrevocable, royalty-free, worldwide licence to use, store, reproduce, process and disclose the Submission for the purposes of evaluating and responding to it, performing any resulting engagement, maintaining business records and complying with law.

5.4 The Company is under no obligation to respond to any Submission, to enter into any engagement, or to treat any Submission as confidential unless a separate written agreement so provides.

## 6. Intellectual Property

6.1 The Website and all content, material, design, layout, text, graphics, images, photographs, audio, video, data, software, code, compilations, descriptors and other elements thereof, and all intellectual property rights therein, are owned by or licensed to the Company and are protected by the laws of India and international treaties.

6.2 The name "Vayasya", the names of the Company's products and services, the Company's logos, marks, trade dress and associated brand elements are trade marks of the Company, whether or not registered. Nothing in these Terms grants any right or licence to use any such trade mark, save for the purposes of attribution under Section 3.2(b) or in accordance with brand guidelines published by the Company.

6.3 Third-party marks, names and content appearing on the Website are the property of their respective owners and are used for identification purposes only.

## 7. Third-Party Links and Services

The Website may contain links to, or integrations with, websites, platforms, applications and services operated by third parties. Such links and integrations are provided for convenience only. The Company does not control, endorse, warrant or assume responsibility for the content, availability, accuracy, security, privacy practices or terms of any third-party website, platform, application or service, and your use thereof is at your own risk and subject to the applicable third-party terms.

## 8. Associated Platforms

Certain platforms, portals, applications and services operated by the Company or its affiliates, including those accessible through subdomains of vayasyaseva.com, are made available under separate terms, agreements or licences ("Platform Terms"). To the extent of any inconsistency between these Terms and the applicable Platform Terms in relation to such platforms, the Platform Terms shall prevail. These Terms shall continue to govern the remainder of the Website.

## 9. Disclaimer of Warranties

9.1 THE WEBSITE AND ALL CONTENT, FUNCTIONALITY, INTERFACES AND SERVICES MADE AVAILABLE THEREON ARE PROVIDED ON AN "AS IS" AND "AS AVAILABLE" BASIS, WITHOUT WARRANTY OF ANY KIND, WHETHER EXPRESS, IMPLIED, STATUTORY OR OTHERWISE.

9.2 TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW, THE COMPANY DISCLAIMS ALL WARRANTIES, INCLUDING WITHOUT LIMITATION WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, NON-INFRINGEMENT, ACCURACY, COMPLETENESS, CURRENCY, RELIABILITY, AVAILABILITY, SECURITY AND FREEDOM FROM ERRORS, VIRUSES OR OTHER HARMFUL COMPONENTS.

9.3 THE COMPANY DOES NOT WARRANT THAT THE WEBSITE WILL BE UNINTERRUPTED, TIMELY, SECURE OR ERROR-FREE, THAT DEFECTS WILL BE CORRECTED, OR THAT THE RESULTS OBTAINED FROM USE OF THE WEBSITE WILL MEET YOUR REQUIREMENTS.

## 10. Limitation of Liability

10.1 TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT SHALL THE COMPANY, ITS AFFILIATES, OR THEIR RESPECTIVE DIRECTORS, OFFICERS, EMPLOYEES, CONTRACTORS, AGENTS, LICENSORS OR SERVICE PROVIDERS BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, EXEMPLARY OR PUNITIVE DAMAGES, OR FOR ANY LOSS OF PROFIT, REVENUE, BUSINESS, GOODWILL, DATA OR ANTICIPATED SAVINGS, ARISING OUT OF OR IN CONNECTION WITH THE WEBSITE, ITS CONTENT, OR THESE TERMS, WHETHER IN CONTRACT, TORT (INCLUDING NEGLIGENCE), BREACH OF STATUTORY DUTY OR OTHERWISE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGES.

10.2 TO THE FULLEST EXTENT PERMITTED BY APPLICABLE LAW, THE AGGREGATE LIABILITY OF THE COMPANY ARISING OUT OF OR IN CONNECTION WITH THE WEBSITE OR THESE TERMS SHALL NOT EXCEED ONE THOUSAND INDIAN RUPEES (INR 1,000).

10.3 Nothing in these Terms excludes or limits any liability that cannot be excluded or limited under applicable law.

## 11. Indemnity

You shall indemnify, defend and hold harmless the Company, its affiliates, and their respective directors, officers, employees, contractors and agents from and against any and all claims, demands, actions, proceedings, liabilities, losses, damages, costs and expenses (including reasonable legal fees) arising out of or in connection with: (a) your access to or use of the Website; (b) any Submission; (c) your breach of these Terms or of any applicable law; or (d) your infringement of any right of a third party.

## 12. Suspension and Termination

The Company may, at its sole discretion and without notice or liability, restrict, suspend or terminate your access to all or any part of the Website, block any Internet Protocol address, user agent or automated system, and take such technical or legal measures as it considers appropriate, whether or not you have breached these Terms. Sections 5, 6, 9, 10, 11, 13 and 14 shall survive any termination.

## 13. Governing Law and Jurisdiction

13.1 These Terms, and any dispute or claim arising out of or in connection with them or with the Website (including non-contractual disputes or claims), shall be governed by and construed in accordance with the laws of India.

13.2 Subject to Section 13.3, the courts at Haridwar, Uttarakhand shall have exclusive jurisdiction over any such dispute or claim, and you irrevocably submit to that jurisdiction.

13.3 Nothing in this Section 13 prevents the Company from seeking injunctive or other equitable relief in any court of competent jurisdiction.

## 14. General Provisions

14.1 **Entire agreement.** These Terms, together with the Privacy Policy and any policies referenced herein, constitute the entire agreement between you and the Company in relation to the Website and supersede all prior understandings in relation thereto.

14.2 **Amendment.** The Company may amend these Terms at any time by publishing the amended Terms on the Website. Amendments are effective upon publication, and the "Last updated" date shall be revised accordingly. Your continued use of the Website following publication constitutes acceptance of the amended Terms.

14.3 **Severability.** If any provision of these Terms is held to be invalid, illegal or unenforceable, that provision shall be enforced to the maximum extent permissible and the remaining provisions shall continue in full force and effect.

14.4 **Waiver.** No failure or delay by the Company in exercising any right or remedy shall operate as a waiver thereof, and no single or partial exercise shall preclude any further exercise.

14.5 **Assignment.** You may not assign or transfer any right or obligation under these Terms without the prior written consent of the Company. The Company may assign or transfer its rights and obligations without restriction.

14.6 **No agency.** Nothing in these Terms creates any partnership, joint venture, agency, fiduciary or employment relationship between you and the Company.

14.7 **Notices.** Notices to the Company shall be sent to the address specified in Section 15. Notices to you may be given by publication on the Website or by any contact detail you have provided.

14.8 **Language.** These Terms are drafted in the English language. Any translation is provided for convenience only, and the English version shall prevail.

## 15. Contact and Company Details

**Vayasya Seva Private Limited**
GSTIN: \`05AAJCV4562E1ZB\`
MSME: \`UDYAM-UK-06-0029670\`
Haridwar, Uttarakhand, India
Electronic mail: help@vayasyaseva.com
Telephone: +91 72920 14101
`;
